"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_g6iw4Np1UuOi3TpbRvr275BZHtbEBnA
"""
import pandas as pd
import seaborn as sns
import seaborn.objects as so
import redis as r
import json
import requests
import yaml
from redis.commands.json.path import Path

def load_config():
    """Load configuration from the YAML file.

    Returns:
        dict: Configuration data.
    """
    with open("config.yaml", "r") as file:
        return yaml.safe_load(file)


config = load_config()


def get_redis_connection():
    """Create a Redis connection using the configuration.

    Returns:
        Redis: Redis connection object.
    """
    return r.Redis(
        host=config["redis"]["host"],
        port=config["redis"]["port"],
        db=0,
        decode_responses=True,
        username=config["redis"]["user"],
        password=config["redis"]["password"],
    )

class RedisAccessor:
    """
    Class: RedisAccessor
    Description: This class stores and retrieves data from Redis.
    """

    def __init__(self):

        """
        Function: Constructor
        Description: Creates an object of type RedisAccessor.
        Arguments: self - the class object
        Returns: None
        """
        self.__redis_connection = get_redis_connection()

        self.__redis_connection.flushall()

    def storeArticles(self, key, articles):
        """
        Function Abstract: storeArticles()
        Description: This function uses Redis' connection to store data in a Python dictionary
                     of articles.
        Arguments: self - the class object
                   key - the index for the articles
                   articles - the articles to store
        Returns: updated_key - the updated numerical key for the articles
        """
        updated_key = key
        for article in articles:
            format_key = f"article:{updated_key}"
            self.__redis_connection.json().set(format_key, Path.root_path(), json.dumps(article))
            updated_key = updated_key + 1
        return updated_key

    def retrieveArticle(self, key):
        """
        Function: retrievearticle()
        Description: This function uses Redis' connection to retrieve an article using a given key.
        Arguments: self - the class object
                   key - the key for the requested article
        Returns: article - the article obtained from Redis for the given key
        """
        article = self.__redis_connection.json().get(key)
        article_data = json.loads(article)
        return article_data

    def populateDataFrame(self):
        """
        Function: populateDataFrame()
        Description: This function returns data obtained from Redis as a dataframe.
        Arguments: self - the class object
        Returns: populated_dataframe - a dataframe containing all the data stored on Redis.
        """
        article_list = []
        for key in self.__redis_connection.scan_iter("article:*"):
            article = self.retrievearticle(key)
            for item in article["source"]:
                source_name = item["name"]
            formatted_row = {
                "Article Title": article["title"],
                "Source Name": source_name,
                "Author": article["author"],
                "Publication Date": article["publishedAt"]
            }
            article_list.append(formatted_row)
        populated_dataframe = pd.DataFrame.from_dict(article_list)
        return populated_dataframe

class NewsApiAccessor:
    """
    Class: NewsApiAccessor
    Description: This class gets data from newsapi
    """
    def __init__(self):
        """
        Function: Constructor
        Description: Creates an object of type RedisAccessor.
        Arguments: self - the class object
        Returns: None
        """
        self

    def getNewsData(self, category_id):
        """
        Function: getNewsData
        Description: Retrieves data from newsapi
        Arguments: self - the class object
                   category_id - the category of news to get the articles from (ie sports, business, entertainment, etc)
        Returns: json_request
        """
        cat_string = 'category=' + category_id + '&'
        url = ('https://newsapi.org/v2/top-headlines?'
              + cat_string +
              'apiKey=5fe8e2f54d2a408bb80b2d573ca73590')
        response = requests.get(url)
        json_request = json.loads(response.json())[type + "s"]["items"]
        if len(json_request) <= 0:
          print("ERROR: could not get json request, sorry about that")
          return None
        return json_request

def main():
  """
  Function: main
  Description: It's the main function that mainly functions.
  """
  red = '#7C1903'
  green = '#52be4f'
  blue = '#2F29BC'

  newsDataAccessor = NewsApiAccessor()
  redisAccessor = RedisAccessor()

  business_news = newsDataAccessor.getNewsData('business')
  sports_news = newsDataAccessor.getNewsData('sports')
  enterainment_news = newsDataAccessor.getNewsData('enterainment')

  key_index = 0
  key_index = redisAccessor.storeArticles(business_news)
  key_index = redisAccessor.storeArticles(sports_news)
  key_index = redisAccessor.storeArticles(enterainment_news)

  article_df = redisAccessor.populateDataFrame()
  source_frequency_df = article_df[["Source Name", "Publication Date"]].copy()
  author_frequency_df = article_df[["Author", "Publication Date"]].copy()
  author_employment_df = article_df[["Source Name", "Author"]].copy()

  so.Plot(data = source_frequency_df, x ='Source Name', y ='Publication Date').add(so.Dot(alpha = 0.5), color = blue).add(so.Line(color = blue)).label(x = "News Source", y = "Publication Date").show()
  so.Plot(data = author_frequency_df, x ='Author', y ='Publication Date').add(so.Dot(alpha = 0.5), color = blue).add(so.Line(color = blue)).label(x = "Author", y = "Publication Date").show()
  so.Plot(data = author_employment_df, x ='Author', y ='Source Name').add(so.Dot(alpha = 0.5), color = blue).add(so.Line(color = blue)).label(x = "Author", y = "News Source").show()

main()